#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peclinic-app
  labels:
    app: peclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peclinic-app
  template:
    metadata:
      labels:
        app: peclinic-app
    spec:
      containers:
      - name: peclinic-app
        image: 268360024445.dkr.ecr.us-west-2.amazonaws.com/petclinic-application:latest-17
        ports:
        - containerPort: 8081
